### ISSUE TITLE
Mac build crashes at startup.

### ISSUE THREAD

**Issue by jonathanff** [ArtemioUrbina/MDFourier#1]
I downloaded the latest build from Junkerhq.net and it crashes instantly when trying to open.
Here are some logs.

![Screen Shot 2020-06-01 at 5 16 32 PM](https://user-images.githubusercontent.com/5711051/83460896-1faaeb00-a42d-11ea-8bbf-ec7435e7cce5.png)

**Comment by ArtemioUrbina** [comment]
Thank you, we've updated the binaries. Could you try them again?

**Comment by donluca** [comment]
@jonathanff let me know if the new version solves your issue.
Writing here so I get notifications about this issue. I'm the maintainer of the macOS version.
